apiVersion: v1
kind: Service
metadata:
  name: dashboard
  namespace: dashboard
  labels:
    app: dashboard
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 80
    targetPort: 3006
  selector:
    app: dashboard
